### ISSUE TITLE
typo in get_phenotypes argument value

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#115]
See includeRels (description below): "historical homologous to" change to "historically homologous to"

includeRels | character or vector of characters. The names of relationships for anatomical entities to include in addition to subtype (rdfs:subClassOf). Defaults to "part of". Set to FALSE to not include any additional relationships. Otherwise one or more of "part of", "historical homologous to", and "serially homologous to", or set to TRUE to include all possible ones. It is acceptable to use unambiguous prefixes, for example "historical".
-- | --

**Comment by hlapp** [comment]
Note that this isn't a typo in the strict sense (as in a misspelling of an argument or argument value). The currently accepted value is in fact `historical homologous to`.

We can change that, but then existing scripts that didn't use "historical" or a shorter unambiguous prefix will break.

**Comment by hlapp** [comment]
Note also that _historical homologous to_ as per RO is the exact synonym of the actual relation [_in historical homology relationship with_](http://purl.obolibrary.org/obo/RO_HOM0000007). I would argue it is unwise to use a label that's different from the actual label or its exact synonym, and that if anywhere, this would need to be fixed upstream first.

I'll thus mark this as not getting fixed for now. We can revisit if and when it is fixed in the ontology.
