### ISSUE TITLE
error using pk_get_iri() with sapply()

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#122]
```
>terms <- readLines("entities_labels.txt") 
> terms_IRIS <- sapply(text = terms, pk_get_iri(), as = "UBERON", exactOnly = TRUE)
Error in match.fun(FUN) : argument "FUN" is missing, with no default
```
[entities_labels.txt](https://github.com/phenoscape/rphenoscape/files/3923870/entities_labels.txt)

**Comment by hlapp** [comment]
This is an R programming error. `terms` has to be the first argument to `sapply()`, not the parameter `text` for the function to be applied. (The parameter `text` of `pk_get_iri` will assume each element of the array as value, because it is the first parameter for that function.) And the function to be applied must be given as the function, not by invoking it. The correct form is this:
```R
terms_IRIS <- sapply(terms, pk_get_iri, as = "UBERON", exactOnly = TRUE)
```

**Comment by wdahdul** [comment]
Thanks Hilmar, it works now with those corrections
