### ISSUE TITLE
Query on OWL expressions

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#14]
It appears that being able to query with an OWL expression doesn't work. RPhenoscape returns this message:

```
Could not find "<http://purl.obolibrary.org/obo/UBERON_0004765> and (<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0008897>" in the database. Please check your input.
```

I was attempting this query: 
```R
nex <- pk_get_ontotrace_xml(taxon = c("Siluriformes"), entity = "<http://purl.obolibrary.org/obo/UBERON_0004765> and (<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0008897>)")
```

**Comment by johnbradley** [comment]
The reason the above command didn't work as expected is the `pk_get_ontotrace_xml` function assumes the `entity` is 
a vector of IRI or a vector of strings that can be resolved into IRI. The pk_get_ontotrace_xml code converts the `entity` input value into an OWL expression.

One option to fix this problem is to change `pk_get_ontotrace_xml` to check the `entity` input value for an owl expression and skip the conversion process.

[Current documentation for pk_get_ontotrace_xml](http://rphenoscape.phenoscape.org/reference/pk_get_ontotrace_xml.html)

**Comment by hlapp** [comment]
Note that the [API meanwhile supports both](https://kb.phenoscape.org/apidocs/#/OntoTrace/post_ontotrace). In principle, if the first token in an OWL expression were reliably an IRI, then one could simply check for this (does string begin with `<https?://`). It would, however, be nice to also be able pass an OWL expression using labels rather than IRIs, and there's an [API endpoint for resolving this to an IRI-based expression](https://kb.phenoscape.org/apidocs/#/Terms/get_term_resolve_label_expression), though then the above pattern for recognition would fail.

I'm thinking that a safer and cleaner method of distinguishing would be if OWL expressions were their own type. I'd have to check whether R allows to give strings additional classes. But it's the S3 mechanism for lists, and it'd be nice to have a tokenized nested list structure representing an OWL expression anyway, which could have a coercion method to string (`as.character()`).

**Comment by hlapp** [comment]
Documentation and examples included here: https://rphenoscape.phenoscape.org/reference/get_ontotrace_data.html
