### ISSUE TITLE
Fix RNeXML links in documentation

### ISSUE THREAD

**Issue by johnbradley** [phenoscape/rphenoscape#186]
The `RNeXML documentation` link in the rphenoscape vignette is no longer valid and results in a 404 webpage. Update the RNeXML link to the new location for this documentation. The correct link is https://docs.ropensci.org/RNeXML/reference/nexml-class.html.

Problematic URL:
https://github.com/phenoscape/rphenoscape/blob/855dee5005e6b31f081c6480dd69f0df8a7b3287/vignettes/rphenoscape.Rmd#L120

See https://github.com/phenoscape/rphenoscape/pull/185#pullrequestreview-619761216 for more.

**Comment by hlapp** [comment]
Note that the line following this is also outdated. And there may be others scattered around. We should try to address all of them.

**Comment by johnbradley** [comment]
@hlapp I updated these two links in rphenoscape.Rmd. Based on a grep the only remaining outdated RNeXML link is in docs/articles/rphenoscape.html. That file seems to be generated from rphenoscape.Rmd. I ran the RStudio "Check", but the docs/articles/rphenoscape.html file wasn't updated. Is there another step to regenerate the html?

**Comment by hlapp** [comment]
You can generate it by hand ("Knit to HTML"), but I think checking the corresponding option in the build config should also work:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/51458/112343182-41fe4580-8c99-11eb-9a82-ab0b8dbdfe8b.png">

**Comment by johnbradley** [comment]
I tried the "Knit to html_vignette" option with rphenoscape.Rmd open in RStudio but it created the HTML file in a temp directory instead of docs/articles/rphenoscape.html
I have slightly different options in my version of RStudio but my settings match what you have above:
<img width="854" alt="Screen Shot 2021-03-24 at 2 12 42 PM" src="https://user-images.githubusercontent.com/1024463/112363745-38320d80-8cac-11eb-9a63-40e49090708d.png">

**Comment by hlapp** [comment]
So did you try checking the "Vignettes" box?

I should have clarified that I normally do not regenerate the HTML from the vignette(s), which is why the box is unchecked for me. For one, it can take time, and also it's regenerated anyway during package generation and installation. The HTML file you found under `docs/` is part of the package website, which is indeed generated as well, but by pkgdown, and normally I only do that as part of a new release.

Here's my build config: 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/51458/112368205-3454ba00-8cb1-11eb-987e-30f978af44bc.png">

**Comment by johnbradley** [comment]
Thanks @hlapp. I will the html file as is on the PR for this issue.

**Comment by johnbradley** [comment]
Fixed by PR #187
