### ISSUE TITLE
RPhenoscape and KB returning different results for a query

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#55]
pk_get_ontotrace_xml(taxon = "Characiformes", entity = "skeletal element") returns 36 characters and 611 taxa

The same query in KB UI (variable only, including parts) returns 100 characters and 630 taxa.

**Comment by balhoff** [comment]
I tried `OWL Expression Input` in the KB UI, and entered the expression `'part of' some 'skeletal element'`. The rPhenosape result is consistent with it sending that expression, instead of what the 'include parts' checkbox does, which is `'skeletal element' or ('part of' some 'skeletal element')`.

In the past (at least a couple years ago), we were treating 'part of' as being reflexive, but we aren't doing this anymore, to be consistent with RO.

**Comment by hlapp** [comment]
> In the past (at least a couple years ago), we were treating 'part of' as being reflexive, but we aren't doing this anymore, to be consistent with RO.

Somehow I missed that change. Was the property never reflexive and had just been treated that way?

**Comment by balhoff** [comment]
I think it was not totally consistent in different declarations. There has been a massive amount of cleanup across ontologies over the last few years and things like this have become much more clear.
